<?php

/**
 * BaseGame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $rules
 * @property integer $players_per_team
 * @property boolean $requires_bnet_id
 * @property string $icon
 * @property Doctrine_Collection $Tournaments
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getRules()            Returns the current record's "rules" value
 * @method integer             getPlayersPerTeam()   Returns the current record's "players_per_team" value
 * @method boolean             getRequiresBnetId()   Returns the current record's "requires_bnet_id" value
 * @method string              getIcon()             Returns the current record's "icon" value
 * @method Doctrine_Collection getTournaments()      Returns the current record's "Tournaments" collection
 * @method Game                setName()             Sets the current record's "name" value
 * @method Game                setRules()            Sets the current record's "rules" value
 * @method Game                setPlayersPerTeam()   Sets the current record's "players_per_team" value
 * @method Game                setRequiresBnetId()   Sets the current record's "requires_bnet_id" value
 * @method Game                setIcon()             Sets the current record's "icon" value
 * @method Game                setTournaments()      Sets the current record's "Tournaments" collection
 * 
 * @package    sfHfLan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('rules', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('players_per_team', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('requires_bnet_id', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('icon', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tournament as Tournaments', array(
             'local' => 'id',
             'foreign' => 'game_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}