<?php

/**
 * BasePartner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $logo
 * @property text $description
 * @property integer $sort_index
 * @property string $url
 * 
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getLogo()        Returns the current record's "logo" value
 * @method text    getDescription() Returns the current record's "description" value
 * @method integer getSortIndex()   Returns the current record's "sort_index" value
 * @method string  getUrl()         Returns the current record's "url" value
 * @method Partner setName()        Sets the current record's "name" value
 * @method Partner setLogo()        Sets the current record's "logo" value
 * @method Partner setDescription() Sets the current record's "description" value
 * @method Partner setSortIndex()   Sets the current record's "sort_index" value
 * @method Partner setUrl()         Sets the current record's "url" value
 * 
 * @package    sfHfLan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partner');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('sort_index', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}