<?php

/**
 * BaseTournament
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $number_of_teams
 * @property integer $prize_pool
 * @property integer $inscription_prize
 * @property integer $event_id
 * @property integer $game_id
 * @property Event $Event
 * @property Game $Game
 * 
 * @method string     getName()              Returns the current record's "name" value
 * @method integer    getNumberOfTeams()     Returns the current record's "number_of_teams" value
 * @method integer    getPrizePool()         Returns the current record's "prize_pool" value
 * @method integer    getInscriptionPrize()  Returns the current record's "inscription_prize" value
 * @method integer    getEventId()           Returns the current record's "event_id" value
 * @method integer    getGameId()            Returns the current record's "game_id" value
 * @method Event      getEvent()             Returns the current record's "Event" value
 * @method Game       getGame()              Returns the current record's "Game" value
 * @method Tournament setName()              Sets the current record's "name" value
 * @method Tournament setNumberOfTeams()     Sets the current record's "number_of_teams" value
 * @method Tournament setPrizePool()         Sets the current record's "prize_pool" value
 * @method Tournament setInscriptionPrize()  Sets the current record's "inscription_prize" value
 * @method Tournament setEventId()           Sets the current record's "event_id" value
 * @method Tournament setGameId()            Sets the current record's "game_id" value
 * @method Tournament setEvent()             Sets the current record's "Event" value
 * @method Tournament setGame()              Sets the current record's "Game" value
 * 
 * @package    sfHfLan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournament extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tournament');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('number_of_teams', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('prize_pool', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('inscription_prize', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('game_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Game', array(
             'local' => 'game_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}