<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $image
 * @property string $url
 * @property string $title
 * @property string $content
 * @property boolean $is_shown
 * @property enum $type
 * 
 * @method string  getImage()    Returns the current record's "image" value
 * @method string  getUrl()      Returns the current record's "url" value
 * @method string  getTitle()    Returns the current record's "title" value
 * @method string  getContent()  Returns the current record's "content" value
 * @method boolean getIsShown()  Returns the current record's "is_shown" value
 * @method enum    getType()     Returns the current record's "type" value
 * @method Article setImage()    Sets the current record's "image" value
 * @method Article setUrl()      Sets the current record's "url" value
 * @method Article setTitle()    Sets the current record's "title" value
 * @method Article setContent()  Sets the current record's "content" value
 * @method Article setIsShown()  Sets the current record's "is_shown" value
 * @method Article setType()     Sets the current record's "type" value
 * 
 * @package    sfHfLan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('is_shown', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'blog',
              1 => 'slider',
             ),
             'default' => 'blog',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $thumbnailable0 = new Thumbnailable(array(
             'thumb_dir' => '%s/.thumbnails',
             'path_method' => 'get%sPath',
             'fields' => 
             array(
              'image' => 
              array(
              'formats' => 
              array(
               'homepage' => '710x319',
              ),
              ),
             ),
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'content',
             ),
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($thumbnailable0);
        $this->actAs($searchable0);
        $this->actAs($sluggable0);
    }
}