<?php

/**
 * ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }
    
    public function getBlogsQuery()
    {
        $query = self::getInstance()
            ->createQuery('a')
            ->leftJoin('a.Category c')
            ->where('c.slug = ?', 'blog')
            ->orderBy('a.created_at DESC');
        
        return $query;
    }
    
    public function getFourLastBlogArticles()
    {
        $query = self::getInstance()->getBlogsQuery()->limit(4);
        return $query->execute();
    }
    
    public function getBlogArticles()
    {
        $query = self::getInstance()->getBlogsQuery();
        return $query->execute();
    }
}