<?php

/**
 * ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }

    public function getPublishedQuery()
    {
      $query = self::getInstance()
        ->createQuery('a')
        ->where("a.is_shown = ?", 1)
        ->orderBy('a.created_at DESC');

      return $query;
    }

    public function getPublishedBlogsQuery()
    {
        $query = $this->getPublishedQuery()
            ->andWhere('a.type = ?', 'blog');
        
        return $query;
    }
    
    public function getPublishedQueryWithSearch($text)
    {
        $query = $this->getPublishedQuery();
        
        $query = $this->search($text, $query);
        
        return $query;
    }
    
    public function getPublishedSliderQuery()
    {
        $query = $this->getPublishedQuery()
          ->andWhere('a.type = ?', 'slider');
        
        return $query;
    }
    
    public function getFourLastBlogArticles()
    {
        $query = self::getInstance()->getPublishedBlogsQuery()
                ->limit(4);
        
        return $query->execute();
    }

    public function getFourLastArticles()
    {
      $query = self::getInstance()->getPublishedQuery()
        ->limit(4);

      return $query->execute();
    }
    
    public function getFourLastSliderArticles()
    {
        $query = self::getInstance()->getPublishedSliderQuery()
                ->limit(4);
        
        return $query->execute();
    }
    
    public function getBlogArticles()
    {
        $query = self::getInstance()->getPublishedBlogsQuery();
        return $query->execute();
    }
}