<?php

/**
 * ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }
    
    public function getPublishedBlogsQuery()
    {
        $query = self::getInstance()
            ->createQuery('a')
            ->where('a.type = ?', 'blog')
            ->andWhere("a.is_shown = ?", 1)
            ->orderBy('a.created_at DESC');
        
        return $query;
    }
    
    public function getPublishedQueryWithSearch($text)
    {
        $query = $this->createQuery('a')
            ->where("a.is_shown = ?", 1)
            ->orderBy('a.created_at DESC');
        
        $query = $this->search($text, $query);
        
        return $query;
    }
    
    public function getPublishedSliderQuery()
    {
        $query = self::getInstance()
            ->createQuery('a')
            ->where('a.type = ?', 'slider')
            ->andWhere("a.is_shown = ?", 1)
            ->orderBy('a.created_at DESC');
        
        return $query;
    }
    
    public function getFourLastBlogArticles()
    {
        $query = self::getInstance()->getPublishedBlogsQuery()
                ->limit(4);
        
        return $query->execute();
    }
    
    public function getFourLastSliderArticles()
    {
        $query = self::getInstance()->getPublishedSliderQuery()
                ->limit(4);
        
        return $query->execute();
    }
    
    public function getBlogArticles()
    {
        $query = self::getInstance()->getPublishedBlogsQuery();
        return $query->execute();
    }
}