<?php

/**
 * MessageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object MessageTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Message');
  }

  public function getOrderedQuery()
  {
    $query = $this->createQuery('m')
      ->orderBy('created_at DESC');

    return $query;
  }

  public function findAllOrdered()
  {
    return $this->getOrderedQuery()->execute();
  }
}