<?php

/**
 * PartnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Partner');
    }
    
    public function getAll()
    {
        $query = self::getInstance()
            ->createQuery('p')
            ->orderBy('p.sort_index ASC');
        
        return $query->execute();
    }
}