<?php

/**
 * SpamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Spam');
    }
}