<?php

/**
 * Tournament
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfHfLan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tournament extends BaseTournament
{
  public function isFull()
  {
    $count = PlayerTable::getInstance()->findByTournamentId($this->getId())->count();

    if($this->getNumberOfTeams() <= 0)
    {
      return false;
    }

    if($count >= $this->getNumberOfTeams() * $this->getPlayersPerTeam())
    {
      return true;
    }

    return false;
  }

  public function getPrizePool()
  {
    return $this->getNumberOfTeams() * $this->getPlayersPerTeam() * $this->getInscriptionPrice();
  }

  public function getSubtournamentPrizePool()
  {
    return $this->getNumberOfTeams() * $this->getPlayersPerTeam() * $this->getSubtournamentInscriptionPrice();
  }

  public function getPlayersPerTeam()
  {
    if($this->hasGame())
    {
      return $this->getGame()->getPlayersPerTeam();
    }
    else
    {
      return 1;
    }
  }

  public function hasGame()
  {
    if($this->getGameId())
    {
      return true;
    }
    else
    {
      return false;
    }
  }
}