<?php

/**
 * Tournament
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfHfLan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tournament extends BaseTournament
{
  public function isFull()
  {
    $count = PlayerTable::getInstance()->findByTournamentId($this->getId())->count();

    if($this->getNumberOfTeams() <= 0)
    {
      return false;
    }

    if(!$this->getGame()->isNew())
    {
      $playersPerTeam = $this->getGame()->getPlayersPerTeam();
    }
    else
    {
      $playersPerTeam = 1;
    }

    if($count >= $this->getNumberOfTeams() * $playersPerTeam)
    {
      return true;
    }

    return false;
  }
}