generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Tournament
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tournament
    with_doctrine_route:   true
    actions_base_class:    sfActions
    theme:                 twitter

    config:
      actions: ~
      fields:  ~
      list:
        title: Gestion des tournois
        display: [=name, number_of_teams, inscription_price, prize_pool]
      filter:  ~
      form:    ~
      edit:
        title: Edition d'un tournoi
      new:
        title: Création d'un tournoi
