generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Event
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      list:
        title: Gestion des évènements
        display: [=name, starts_at, entry_price]
        fields:
          starts_at:
            label: Date
      filter:  ~
      form:    ~
      edit:
        title: Edition d'un évènement
      new:
        title: Création d'un évènement
