generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Player
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          player
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Gestion des articles
        display: [=firstname, =lastname, created_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
