generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Player
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          player
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Gestion des joueurs
        display: [=firstname, =lastname, nickname, Team, email, created_at]
        actions:
          _new: ~
          booking: { label: Booking }
          mailingList: { label: Generate Mailing-List }
          exportCsv: { label: Export to CSV }
          #print: { label: Print }
      filter:  ~
      form:
        display:
          - firstname
          - lastname
          - nickname
          - email
          - team
          - team_tag
          - tournament_id
          - bnet_email
          - bnet_ccode
          - pc_type
          - wants_cable
          - subtournament
          - _token
      edit:    ~
      new:     ~
