generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Game
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          game
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Gestion des jeux
        display: [icon, =name, players_per_team]
      filter:  ~
      form:    ~
      edit:
        title: Edition d'un jeu
      new:
        title: Création d'un jeu
