# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=sfHfLan
      username: root
      password: 
        
prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=mysql51-53.perso;dbname=mattscantdb
      username: mattscantdb
      password: E4RT6YGF
