<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tournament', 'bracket_image', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tournament', 'bracket_image');
    }
}