<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tournament', 'embedded_player', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tournament', 'embedded_player');
    }
}