generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Article
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          article
    with_doctrine_route:   true
    actions_base_class:    sfActions
    theme:                 twitter

    config:
      actions: ~
      fields:
        is_shown :
          label: Publié ?
      list:
        title: Gestion des articles
        display: [=title, created_at, type, is_shown]
        batch_actions:
          _delete:    ~
          show: 
            label: Publier
          mask:
            label: Masquer
        object_actions:
          _edit:      ~
          _delete:    ~
          show: 
            label: Publier
          mask:
            label: Masquer
      filter:  ~
      form:
        display:
          Contenu: [title, content, url, image, is_shown, type]
          
      edit:
        title: Edition d'un article
      new:
        title: Création d'un article
