generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Partner
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          partner
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Gestion des partenaires
        display: [sort_index, =name, url]
      filter:  ~
      form:    ~
      edit:
        title: Edition d'un partenaire
      new:
        title: Création d'un partenaire
